image:
  repository: "ghcr.io/saoudimehdi/spring-petclinic"
  pullPolicy: IfNotPresent

replicas: 1

autoscaling:
  enabled: false

app:
  contextPath: ""

service:
  type: ClusterIP
  port: 8080

serviceAccount:
  create: false