apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
images:
- name: ghcr.io/saoudimehdi/spring-petclinic
  newName: ghcr.io/saoudimehdi/spring-petclinic
  newTag: 4.0.1-SNAPSHOT
- name: spring-petclinic
  newName: ghcr.io/saoudimehdi/spring-petclinic
  newTag: 723090185906f120f9ae5e12dc7bd953af167d44
patches:
- path: replicas.yaml
  target:
    group: apps
    kind: Deployment
    name: spring-petclinic
    version: v1
- path: patch-routing.yaml
  target:
    group: apps
    kind: Deployment
    name: spring-petclinic
    version: v1
- patch: |-
    - op: replace
      path: /spec/rules/0/http/paths/0/path
      value: /tp7
  target:
    group: networking.k8s.io
    kind: Ingress
    name: spring-petclinic
    version: v1
