apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic
spec:
  template:
    spec:
      containers:
        - name: spring-petclinic
          startupProbe:
            httpGet:
              path: /tp7/
          livenessProbe:
            httpGet:
              path: /tp7/actuator/health/liveness
          readinessProbe:
            httpGet:
              path: /tp7/actuator/health/readiness
          env:
            - name: SERVER_SERVLET_CONTEXT_PATH
              value: /tp7